config/routes.rb
SnailDemo::Application.routes.draw do
  

  get 'kindeditor/images_list'
  post 'kindeditor/upload'
  match 'users/:id/faq/edit' => 'faq#edit'

  match 'users/:id/contact/edit' => 'contact#edit'

  match 'users/:id/spec/edit' => 'spec#edit'

  devise_for :users

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
  end    

    resources :users do
      resources :profile, :only => ['index']
      resources :albums do
        resources :photos
      end
      resources :posts
      resources :comments
      resources :friendship, :only => ['index','accept','create','decline','cancle','delete']
      resources :twitters
   end

  root :to => 'pages#home'

  match '/about' => "pages#about"

  match '/help' => "pages#help"

end

app/models/user.rb
# == Schema Information
# Schema version: 20110427021741
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean(1)
#  name                   :string(255)
#  actived                :boolean(1)
#

class User < ActiveRecord::Base
  #关联微博
  has_many :twitters, :dependent => :destroy
  #好友关联
  has_many :friendships, :dependent => :destroy
  has_many :friends, 
           :through => :friendships,
           :conditions => "status = 'accepted'",
           :order => :name

  has_many :requested_friends,
           :through => :friendships,
           :source => :friend,
           :conditions => "status = 'requested'",
           :order => :created_at

  has_many :pending_friends,
           :through => :friendships,
           :source => :friend,
           :conditions => "status = 'pending'",
           :order => :created_at

  #评论关联
  has_many :comments, :dependent => :destroy
  #博客关联
  has_many :posts,  :dependent => :destroy
  #相册关联
  has_many :albums, :dependent => :destroy
  #个人信息关联
  has_one :faq,     :dependent => :destroy
  #关联基本资料spec
  has_one :spec,    :dependent => :destroy
  #关联联系方式contact
  has_one :contact, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for user model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  #attributes Validation 
  validates :name,:presence => true,:length => {:within => 2..10 }
  #email格式匹配在devise.rb中进行了配置
end

app/controllers/users_controller.rb
#encoding:utf-8
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.xml {render :xml => @user}
    end
  end
  
  def index
    @users = User.paginate(:per_page => 20, :page => params[:page])
     respond_to do |format|
      format.html
      format.xml {render :xml => @users}
     end
    end
end


app/views/users/_home_middle.html.erb
<div class="col col_10"><!-- middle Part -->
  <!-- new microblog form -->
  <%= render 'twitters/form' %>
  <div class="feeds">
    <div class="author">DHH</div>
    <div class='content'>DHH is a good guy.</div>
  </div>

  <div class="feeds">
    <div class="author">李开复</div>
    <div class='content'>中国的未来互联网依然是蓝海，电子商务，移动互联网，云计算。</div>
  </div>

   <div class="feeds">
    <div class="author">马云</div>
    <div class="content">来自杭州的软件业界应该团结起来，共同合作，为中国互联网的发展创造合力，而不是互相内斗，损耗。不要学习360和腾讯的做法。</div>
  </div>

</div><!-- end of middle -->


app/views/users/_left_menu.html.erb
<div class="col col_3"><!-- Left Part -->

  <!-- Avatar -->
  <div class="avatar align_center">
    <%= link_to image_tag('avatar.png'),@user %>
    <h3><%= @user.name %></h3>
  </div>

  <div class="operation">
    <ul>
      <li>
      <%= link_to new_user_post_path(@user) do %>
        <%= image_tag 'article.png', :size => '20x20' %>发表日志
      <% end %>
      </li>

      <li>
      <%= link_to user_albums_path(@user) do %>
        <%= image_tag 'picture.png', :size => '20x20' %>上传图片
      <% end %>          
      </li>

      <li>
        <%= link_to user_profile_index_path(@user)  do %>
          <%= image_tag 'modify.png', :size => '20x20' %>个人资料
        <% end %>
      </li>

      <li>
      <%= link_to '#' do %>
        <%= image_tag 'message.png', :size => '20x20' %>消息管理
      <% end %>
      </li>
    </ul>

  </div>

</div><!-- end of left-->


app/views/users/_middle.html.erb
<div class="col col_10"><!-- middle Part -->
  <% if @user == current_user %>
  <!-- new microblog form -->
  <%= render 'twitters/form' %>
 <% end %>

  <%= render 'friendship/friend' %>

  <div class="feeds">
    <div class="author"><%= @user.name %></div>
    <div class="content">DHH is a good guy.</div>
  </div>

  <div class="feeds">
    <div class="author"><%= @user.name %></div>
    <div class="content">中国的未来互联网依然是蓝海，电子商务，移动互联网，云计算。</div>
  </div>

   <div class="feeds">
     <div class="author"><%= @user.name %></div>
     <div class="content">来自杭州的软件业界应该团结起来，共同合作，为中国互联网的发展创造合力，而不是互相内斗，损耗。不要学习360和腾讯的做法。</div>
  </div>

</div><!-- end of middle -->


app/views/users/_right_menu.html.erb

<div class="col col_3"><!-- right part -->
  <!-- Recent Visitors -->
  <div class="visitors">
    <span>最近来访:</span>
    <ul>
      <li>马云</li>
      <li>李开复</li>
      <li>断保研</li>
      <li>欺实马</li>
    </ul>
  </div>

  <!-- All the friends -->
  <div class="friends">
    <span>所有好友:</span>
    <ul>
      <li>比尔·盖茨</li>
      <li>巴菲特</li>
      <li>段包烟</li>
    </ul>
  </div>
</div><!-- end of right -->


app/views/users/_visitor_left_menu.html.erb
<div class="col col_3"><!-- Left Part -->

  <!-- Avatar -->
  <div class="avatar align_center">
    <%= link_to image_tag('avatar.png'),@user %>
    <h3><%= @user.name %></h3>
  </div>

  <div class="operation">
    <ul>
      <li>
      <%= link_to user_posts_path(@user) do %>
        <%= image_tag 'article.png', :size => '20x20' %>日志
      <% end %>
      </li>

      <li>
      <%= link_to user_albums_path(@user) do %>
        <%= image_tag 'picture.png', :size => '20x20' %>相册
      <% end %>          
      </li>

       <li>
        <%= link_to user_profile_index_path(@user)  do %>
          <%= image_tag 'modify.png', :size => '20x20' %>个人资料
        <% end %>
      </li>


    </ul>

  </div>

</div><!-- end of left-->



app/views/users/show.html.erb
<!-- if the user is the owner then show the edit operatiron, else just show some links -->
<% if @user == current_user %>
  <%= render 'left_menu' %>
<% else %>
  <%= render 'visitor_left_menu' %>
<% end %>

<%= render 'middle' %>
<%= render 'right_menu' %>