config/routes.rb
SnailDemo::Application.routes.draw do
  

  get 'kindeditor/images_list'
  post 'kindeditor/upload'
  match 'users/:id/faq/edit' => 'faq#edit'

  match 'users/:id/contact/edit' => 'contact#edit'

  match 'users/:id/spec/edit' => 'spec#edit'

  devise_for :users

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
  end    

    resources :users do
      resources :profile, :only => ['index']
      resources :albums do
        resources :photos
      end
      resources :posts
      resources :comments
      resources :friendship, :only => ['index','accept','create','decline','cancle','delete']
      resources :twitters
   end

  root :to => 'pages#home'

  match '/about' => "pages#about"

  match '/help' => "pages#help"

end

app/models/photo.rb
#encoding: utf-8
# == Schema Information
# Schema version: 20110505023421
#
# Table name: photos
#
#  id                 :integer(4)      not null, primary key
#  album_id           :integer(4)
#  description        :string(255)     default("")
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer(4)
#  image_updated_at   :datetime
#

class Photo < ActiveRecord::Base
  #设置可访问性
  attr_accessible :image, :album_id, :description
  
  #关联相册
  belongs_to :album
  #关联评论
  has_many :comments, :dependent => :destroy


  #图片的保存路径形式/public/uploads/<用户ID>/:style/:after_file_name.:extension
  has_attached_file :image, :styles => { :thumb => '100x100'},
                            :path => ":rails_root/public/uploads/:albumid/:style/:after_file_name.:extension",
                            :url => "/uploads/:albumid/:style/:after_file_name.:extension"

  #对格式进行校验
 # validates_attachment_presence :image
  #validates_attachment_size :image, :less_than => 5.megabytes
 # validates_attachment_content_type :image, :content_type => ['image/jpeg','image/jpg', 'image/png', 'image/gif']

  #:after_file_name的自定义解析
  Paperclip.interpolates :after_file_name do |attachment,style|
      attachment.instance.after_file_name
  end

  Paperclip.interpolates :albumid do |attachment,style|
    attachment.instance.album_id
  end
  
  #此处的方法必须是公有的，否则会报错
   def after_file_name
     #包含UUID相关的库
     require 'uuidtools'
     UUIDTools::UUID.parse_raw("#{self.image_file_name}").to_s.gsub(/-/,'')
     #SecureRandom.uuid.gsub(/-/,'')
  end


end

app/controllers/photos_controller.rb
#encoding: utf-8
class PhotosController < ApplicationController
   #需要用户登录，才可以进行修改
  before_filter :authenticate_user!

  # GET /photos
  # GET /photos.xml
  def index
    @user = User.find(params[:user_id])
    @album = Album.find(params[:album_id])
    @photos = @album.photos

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @user = User.find(params[:user_id])
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])
    puts '**********user_id:'+params[:user_id].to_s+",album_id:"+params[:album_id].to_s+",photo_id:"+params[:id].to_s

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => [@user,@album,@photo] }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @user = current_user
    @album = Album.find(params[:album_id])
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @user = current_user
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    @user = current_user
    @album = Album.find(params[:album_id])

    newparams = coerce(params)

    @photo = Photo.new(newparams[:photo])



    respond_to do |format|
      if @photo.save
       # puts '********It is saved****************'
        format.html { redirect_to([@user,@album,@photo], :notice => 'Photo was successfully created.') }
        format.json  { render :json => { :result => 'success', :photo => @photo } }
      else
        redirect_to user_album_url(@user,@album) 
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @user = current_user
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to([@user,@album,@photo], :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html {  redirect_to user_album_url(@user,@album)  }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @user = current_user
    @album = Album.find(params[:album_id])
    @photo = Photo.find(params[:id])
    @photo.image.clear
    @photo.destroy


    respond_to do |format|
      format.html { redirect_to(user_album_url([@user,@album])) }
      format.xml  { head :ok }
    end
  end


  private 

  def coerce(params)
    if params[:photo].nil? 
      h = Hash.new 
      h[:photo] = Hash.new 
      h[:photo][:album_id] = params[:album_id] 
      h[:photo][:image] = params[:Filedata] 
      h[:photo][:image].content_type = MIME::Types.type_for(h[:photo][:image].original_filename).to_s
      h
    else 
      params
    end 
  end


end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_id %><br />
    <%= f.text_field :album_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<%= content_tag_for(:li, photo) do %>

  <%= link_to photo.image.url do %>
    <%= image_tag photo.image.url(:thumb), :alt => "#{photo.description}" %>
  <% end %>

<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Album</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.description %></td>
    <td><%= link_to 'Show', [@user,@album,photo] %></td>
    <td><%= link_to 'Edit', edit_user_album_photo_path(photo,@album,@user) %></td>
    <td><%= link_to 'Destroy', [@user,@album,photo], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.js.erb
$('#photos').append("<%= escape_javascript(render(:partial => 'photos/photo',:locals => {:photo => @photo })) %>");
