config/routes.rb
SnailDemo::Application.routes.draw do
  

  get 'kindeditor/images_list'
  post 'kindeditor/upload'
  match 'users/:id/faq/edit' => 'faq#edit'

  match 'users/:id/contact/edit' => 'contact#edit'

  match 'users/:id/spec/edit' => 'spec#edit'

  devise_for :users

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
  end    

    resources :users do
      resources :profile, :only => ['index']
      resources :albums do
        resources :photos
      end
      resources :posts
      resources :comments
      resources :friendship, :only => ['index','accept','create','decline','cancle','delete']
      resources :twitters
   end

  root :to => 'pages#home'

  match '/about' => "pages#about"

  match '/help' => "pages#help"

end

app/models/post.rb
# == Schema Information
# Schema version: 20110509011902
#
# Table name: posts
#
#  id         :integer(4)      not null, primary key
#  user_id    :integer(4)
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  attr_accessible :title, :body, :user_id

  belongs_to :user
  has_many :comments, :dependent => :destroy
end

app/controllers/posts_controller.rb
#encoding: utf-8
class PostsController < ApplicationController
  #需要用户登录，才可以进行修改
  before_filter :authenticate_user!


  # GET /posts
  # GET /posts.xml
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.paginate(:per_page => 7, :page => params[:page]) || Comment.new
    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @user = current_user
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @user = current_user
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @user = current_user
    @post = Post.new(params[:post])
    @post.user = @user

    respond_to do |format|
      if @post.save
        format.html { redirect_to([@user,@post], :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => ([@user,@post]) }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @user = current_user
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(([@user,@post]), :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @user = current_user
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(user_posts_url(@user)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= kindeditor_javacript_include_tag %>
<%= form_for([@user,@post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="textarea">
    <%= f.label :body %>:<br />
    <%= f.text_area :body,:id => 'kindeditor' %>

    <div class="submit">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="col col_14">

<h1>Editing post</h1>

<div class="posts">
  <%= render 'form' %>
</div>

<%= link_to 'Show', user_post_path(@user,@post) %> |
<%= link_to 'Back', user_posts_path(@user) %>
</div>

app/views/posts/index.html.erb
<%= kindeditor_javacript_include_tag %>

<h1>Listing posts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.user_id %></td>
    <td><%= post.title %></td>
    <td><%= link_to 'Show', user_post_path(@user,post) %></td>
    <td><%= link_to 'Edit', edit_user_post_path(@user,post) %></td>
    <td><%= link_to 'Destroy', [@user,post], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_user_post_path %>

app/views/posts/new.html.erb
<div class='col col_14'>

<h1>New post</h1>

<div class="posts">
  <%= render 'form' %>
</div>

<%= link_to 'Back', user_posts_path(@user) %>
</div>

app/views/posts/show.html.erb
<div class="post-show">
  <p id="notice"><%= notice %></p>

  <div class='title'>
   <h2> <%= @post.title %></h2>
  </div>

    <%= raw(@post.body) %>

  <%= link_to 'Edit', edit_user_post_path(@user,@post) %> |
  <%= link_to 'Back', user_posts_path(@user) %>
</div>


<div class="comments">
  <div><h3>Comments:</h3></div>
  <ul id="comments">
    <%= render :partial => @comments %>
  </ul>
  <%= will_paginate(@comments) %>
</div>


<div class="comments_form">
  <%= form_for([@user,Comment.new], :remote => true) do |f| %>
    <%= f.hidden_field :user_id, :value => @post.user_id %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <%= f.hidden_field :commentor, :value => current_user.name %>
    <%= f.hidden_field :commentor_id, :value => current_user.id %>
    <%= f.hidden_field :subject, :value => @post.title %>
    <%= f.hidden_field :kind, :value => Comment::POST_COMMENT %>
    <div>
      <%= f.label :body %>:<br/>
      <%= f.text_area :body %><br/>
      <%=f.submit %>
    </div>
  <% end %>
</div>