config/routes.rb
SnailDemo::Application.routes.draw do
  

  get 'kindeditor/images_list'
  post 'kindeditor/upload'
  match 'users/:id/faq/edit' => 'faq#edit'

  match 'users/:id/contact/edit' => 'contact#edit'

  match 'users/:id/spec/edit' => 'spec#edit'

  devise_for :users

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
  end    

    resources :users do
      resources :profile, :only => ['index']
      resources :albums do
        resources :photos
      end
      resources :posts
      resources :comments
      resources :friendship, :only => ['index','accept','create','decline','cancle','delete']
      resources :twitters
   end

  root :to => 'pages#home'

  match '/about' => "pages#about"

  match '/help' => "pages#help"

end

app/views/layouts/_footer.html.erb
<hr/>
<%= render 'layouts/nav_footer' %>
<p style="float:right;"> 
  All Right Reserved &copy; 奋斗的蜗牛工作室 2011-2012<br/>
  地址:西安市太白路兴隆段266号西安电子科技大学长安新校区 邮编；710126
</p>

app/views/layouts/_header.html.erb
  <div class="col col_5">
    <%= link_to logo,root_path %>
  </div><!-- end of logo -->

    <%= render 'layouts/nav' %>
  <!-- end of navigator -->

<div class="clear"></div><!--clear-->

app/views/layouts/_menu_right.html.erb
<li class="last">
<%= image_tag 'corner_left.png', :class => 'corner_left' %>
<%= image_tag 'dot.gif', :class => 'middle' %>
<%= image_tag 'corner_right.png', :class => 'corner_right' %>
</li>


app/views/layouts/_nav.html.erb
<nav class="col col_11">
  <ul id="menu">    
    <% if current_user.nil? %>
      <li><%= link_to 'Home',root_path %></li>
      <li><%= link_to 'Sign in',login_path %></li>
      <li><%= link_to 'Sign up',signup_path %></li>
    <% else %>
      <li><%= link_to 'Home',root_path %></li>      
      <li>
      <%= link_to 'Personal' %>
      <ul style="display:none;" class="subnav">
        <li>
        <%= image_tag 'corner_inset_left.png', :class => 'corner_inset_left' %>
        <%= link_to 'Theme','#' %>
        <%= image_tag 'corner_inset_right.png', :class => 'corner_inset_right' %>
        </li>
        <li><%= link_to 'Profile',"/users/#{current_user.id}/profile" %></li>
        <%= render 'layouts/menu_right' %>
      </ul>
      </li>

      <li>
      <%= link_to 'Friends', '#' %>
      <ul>
        <li>
        <%= image_tag 'corner_inset_left.png', :class => 'corner_inset_left' %>
        <%= link_to 'Search','#' %>
        <%= image_tag 'corner_inset_right.png', :class => 'corner_inset_right'%>
        </li>
        <li><%= link_to 'Manage','*' %></li>
        <%= render 'layouts/menu_right' %> 
      </ul>
      </li>


      <li>
        <%= link_to 'Applies','#' %>
      	<ul>
          <li>
          <%= image_tag 'corner_inset_left.png', :class => 'corner_inset_left' %>
            <%= link_to 'Posts',user_posts_path(current_user) %>
            <%= image_tag 'corner_inset_right.png', :class => 'corner_inset_right' %>
          </li>
          <li>
            <%= link_to 'Albums',user_albums_path(current_user) %>
          </li>
          <li>
            <%= link_to 'Messages','#' %>
          </li>
          <%= render 'layouts/menu_right' %>
      	</ul>
      </li>

      <li><%= link_to 'Logout',logout_path %></li>
    <% end %>
    <li><%= link_to 'About us',about_path %></li>
    <li><%= link_to 'Help',help_path %></li>
    <% unless current_user.nil? %>
    <li class="searchContainer">
    <div>
      <input type="text" id="searchField"/>
      <%= image_tag 'find.png', :onclick => "alert('You have click search')"%>
    </div>
    </li>
  <% end %>
  </ul>
</nav>

app/views/layouts/_nav_footer.html.erb
<nav>
  <style>
    #footer_menu>li {float: left; width: 90px; display:block;}
    #footer_menu li a { text-decoration:none;}
    #footer_menu li a:hover {color:#B0D730;}
  </style>
  <ul id="footer_menu">
    <li><%= link_to 'Home',root_path %></li>
    <% if current_user.nil? %>
      <li><%= link_to 'Sign in',login_path %></li>
      <li><%= link_to 'Sign up',signup_path %></li>
    <% else %>
      <li><%= link_to 'Logout',logout_path%></li> 
    <% end %>
    <li><%= link_to 'About us',about_path %></li>
    <li><%= link_to 'Help',help_path %></li>
  </ul>
</nav>


app/views/layouts/_stylesheets.html.erb
<!-- JS Files -->
<%= javascript_include_tag :defaults %>
<%= javascript_include_tag 'jquery-ui.min'%>
<%= javascript_include_tag 'modernizr' %>
<!--CSS Files -->
<%= stylesheet_link_tag 'reset', :media => 'screen' %>
<%= stylesheet_link_tag 'css3', :media => 'screen' %>
<%= stylesheet_link_tag 'general', :media => 'screen' %>
<%= stylesheet_link_tag 'grid', :media => 'screen' %>
<%= stylesheet_link_tag 'forms', :media => 'screen' %>
<%= stylesheet_link_tag 'menu', :media => 'screen' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

<!-- Self-define CSS -->
<%# <style> %>
  <%# /*header .logo { height: 40px; float: left; width: 120px;margin-top:12px;} %>
  <%# header { padding-top: 5px; border-bottom: 1px solid #ccc; padding-bottom: 10px;}*/ %>
  <%# /*nav ul li{float: left; margin-top:12px;width: 80px; text-align:center;} %>
  <%# nav ul li a{ display: block; padding: 5px 15px; border-right: 1px solid #eee; font-size: 1.2em; text-decoration: none;} %>
  <%# nav ul li a:hover { background: #ccc; border-right: 1px solid #eee; text-shadow: -1px -1px 0px #fff;}*/ %>
<%# </style> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="row">
      <header>
        <%= render 'layouts/header' %>
      </header><!-- end of header -->
    </div>

    <section class="row">
      <div class="documentation">
        <div class="notice">
          <%= flash[:notice] %>
        </div>
        <div class="alert">
          <%= flash[:alert] %>
        </div>
      </div>
        <%= yield %>
    </section><!-- end of section -->


    <footer class="row">
      <%= render 'layouts/footer' %>
    </footer><!-- end of footer-->
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>